# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46a82f58aa9c861030f8a9d040159882c55bff2664466dfb8a2caebca84a4d50458474417b2c4d23c37d91f988e1d55d0f034100fec6eb5e0af6520b64d23d5c

test:
  secret_key_base: 64dda25672f69172af088e834885d94bdaccb3a1cab8c55cddc3b5905bc649ae593825a50d1fef41befc93c15e6fc414b798513cf62388f9a9c4a7b5d6cb35ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
